 
version: '3.8'
services:
  notification:
    image: ghcr.io/nervus-tech/nervus-notification:v1.0.0
    ports:
      - "8102:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/nervus
      - SPRING_DATASOURCE_USERNAME=nervus_user
      - SPRING_DATASOURCE_PASSWORD=secure_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=notification
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CONSUMER_TOPIC=notifications
      - SENDGRID_API_KEY=your_sendgrid_api_key
    depends_on:
      - postgres
      - kafka
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=nervus
      - POSTGRES_USER=nervus_user
      - POSTGRES_PASSWORD=secure_password
    ports:
      - "5437:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
volumes:
  pgdata: 